x-rbw-auto-base: &rbw-auto-base
  image: ghcr.io/pschmitt/rbw-auto:latest
  build: .
  restart: no
  env_file:
    - secrets.env
  volumes:
    # persistent storage
    - ./data:/data
    # devel
    - ./bw-backup.sh:/usr/local/bin/rbw-auto-backup:ro
    - ./bw-sync.sh:/usr/local/bin/rbw-auto-sync:ro
    - ./entrypoint.sh:/entrypoint.sh:ro
    - ./lib.sh:/usr/local/bin/lib.sh:ro

services:
  rbw-auto-backup:
    <<: *rbw-auto-base
    container_name: rbw-auto-backup
    command: backup

  rbw-auto-sync:
    <<: *rbw-auto-base
    container_name: rbw-auto-sync
    command: sync
